# Generated by Django 4.2.14 on 2024-08-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollars')], default='INR', max_length=255),
        ),
    ]
